package com.bjpowernode.p2p.mapper.loan;


import com.bjpowernode.p2p.model.loan.BidInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 16:37:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 16:37:59 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 16:37:59 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 16:37:59 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 16:37:59 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Fri Feb 22 16:37:59 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);

    Double selectAllBidMoney();

    List<BidInfo> selectBidInfoListLoanId(Integer loanId);


    List<BidInfo> selectBidInfoByPage(Map<String, Object> map);

    Long selectTotal(Map<String, Object> map);

    List<BidInfo> selectBidInfoByLoanId(Integer loanId);
}