chinags:
  name: auth  #系统的名称，必填
server:
  port: 9912
spring:
  zipkin:
    base-url: http://127.0.0.1:9921
  application:
    name: service-auth #指定服务名
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.2:1521:orcl
    username: base
    password: base
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 30000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  jpa:
    database: oracle
    show-sql: true
    format_sql: true
    use_sql_comments: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect #jpa方言
#    hibernate:
#      ddl-auto: update
  jackson:
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9900/eureka/
  instance:
    prefer-ip-address: true

swagger:
  base-package: com.chinags
#初始密码，默认123456
#initpassword: 123456

redis:
  password: 123456
  timeout:
    menu: 86400 #菜单key超时时间
  keyName: jd-ds-menus #菜单keyName

encryption: jd-ds-j #加密字符
logging:
  level:
    root: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace  #打印sql参数
  file: E:/logs/auth/auth.log

